### ISSUE TITLE
为啥翻译别人的文章不把原文带上

### ISSUE THREAD

**Issue by flag007** [taielab/Taie-Bugbounty-killer#2]
为啥翻译别人的文章不把原文带上
https://www.infosecmatter.com/bug-bounty-tips-1/
为啥翻译别人的文章不把原文带上
https://www.infosecmatter.com/bug-bounty-tips-1/
为啥翻译别人的文章不把原文带上
https://www.infosecmatter.com/bug-bounty-tips-1/
为啥翻译别人的文章不把原文带上
https://www.infosecmatter.com/bug-bounty-tips-1/

**Comment by taielab** [comment]
已更新原文出处，感谢错误指正。
